#!/usr/bin/env bash
# install nginx web server
# Listen on port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
