#!/usr/bin/env bash
# install nginx web server
# Listen on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
