#!/usr/bin/env bash
# Configure an Nginx server so that /redirect_me redirets to another page.
# The redirection is configured as "301" Moved Permanently.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure nginx server
default_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn location $default_sites | head -1 | cut -d";" -f1)
location_data="\\\tlocation /redirect_me {\n\t\treturn 301 https://github.com/mubarakoluwasheun;\n\t}\n\n"

## Update default site to redirect and start nginx server
sudo sed -i "${location}i ${location_data}" ${default_sites}
sudo service nginx start