#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Update package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Modify the default Nginx configuration to add a custom 404 page and redirect rule
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Tolulope05 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# Add the custom header to the Nginx configuration
sed -i "/server_name _;/a \    add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default

# Start and reload Nginx to apply the changes
service nginx start
service nginx reload
