#!/usr/bin/env bash
# This script is display the time in hours and minutes
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo $minute
        minute=$((minute+1))
    done
    hour=$((hour+1))
done
